// resources/js/vue/user/layout.vue
<template>
    <HeaderComp />
    <router-view></router-view>
    <FooterComp />
</template>
<script>
import HeaderComp from "./components/header/comp.vue";
import FooterComp from "./components/footer/comp.vue";

export default {
    name: "user-layout",
    components: {
        HeaderComp,
        FooterComp,
    },
};
</script>

// resources/js/react/user/layout.js
import { Outlet } from "react-router-dom";

// importing default components
import Header from "./components/header/comp";
import Footer from "./components/footer/comp";

export default function Layout() {
    return (
        <>
            <Header />
            <Outlet />
            <Footer />
        </>
    );
}
