// resources/js/react/admin/layout.js
import { Outlet } from "react-router-dom";

// importing default components
import Sidebar from "./components/sidebar/comp";
import Header from "./components/header/comp";
import Footer from "./components/footer/comp";
// import Auth from "../assets/auth";

// import CSS
import CSS from "./layout.module.css";

export default function Layout() {
    return (
        <>
            <main className={CSS.admin_layout}>
                <Sidebar />
                <div className={CSS.main_container}>
                    <Header />
                    <main className={CSS.main_content}>
                        <Outlet />
                    </main>
                    <Footer />
                </div>
            </main>
        </>
    );
}

// resources/js/vue/user/layout.vue
<template>
    <HeaderComp />
    <router-view></router-view>
    <FooterComp />
</template>
<script>
import HeaderComp from "./components/header/comp.vue";
import FooterComp from "./components/footer/comp.vue";

export default {
    name: "user-layout",
    components: {
        HeaderComp,
        FooterComp,
    },
};
</script>
