// resources/js/react/user/components/header/comp.js
import { Link } from "react-router-dom";
import "/public/css/components/header.css";

export default function () {
    return (
        <header className="rflex jcsb aic">
            <h6>header</h6>
            <nav className="rflex">
                <Link to="/" className="mu-link">
                    Home
                </Link>
                <Link to="about" className="mu-link">
                    About Us
                </Link>
            </nav>
        </header>
    );
}

// resources/js/vue/user/components/header/comp.vue
<template>
    <header class="rflex jcsb aic">
        <h6>header</h6>
        <nav class="rflex">
            <router-link to="/" class="mu-link">Home</router-link>
            <router-link to="about" class="mu-link">About Us</router-link>
        </nav>
    </header>
</template>
<script>
export default {
    name: "header-comp",
};
</script>
<style scoped>
@import url("/public/css/components/header.css");
</style>
